### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by DearMadMan** [mrliptontea/sublime-text-sidebar-icons#1]
nice job ,but ... i don't understand to how use it...
is so hard to match...

**Comment by mrliptontea** [comment]
First of all, you need:
- [Sublime Text 3](http://sublimetext.com/3) editor,
- Installed and enabled theme that supports file type icons in the sidebar, for example one from the list in the [readme](/mrliptontea/sublime-text-sidebar-icons#installation).

#### How to install
1. Open Sublime Text and select "Preferences" > "Browser packages..." - it will open a folder for user packages.
2. Clone or download and unzip this repo to this folder.
3. Rename `sublime-text-sidebar-icons` to name that matches your theme name.
4. Restart Sublime to reload all icons.

#### Example

Now I have [Material Theme](https://packagecontrol.io/packages/Material%20Theme) installed. My directory structure looks like this:

```
Sublime Text 3\
|-- Data\
|   |-- Cache\
|   |-- Index\
|   |-- Installed Packages\
|   |   |-- Material Theme.sublime-package  <-- theme installed via Package Control
|   |   |-- ...
|   |-- Local\
|   |-- Packages\
|   |   |-- Material Theme\                 <-- here I put my icons
|   |   |   |-- icons\
|   |   |   |-- Prefs\
|   |   |-- some other packages...
```

#### Note

Alas, the file structure in a theme can be different, and that will prevent overwriting its icons.
In that case, you should look into `Sublime Text 3/Data/Installed Packages/[Theme - name].sublime-package` file (just unzip it) and check where the `.tmPreferences` files reside, sometimes they are in the `icons` folder.

Hope this will help :wink:

**Comment by DearMadMan** [comment]
thinks,You have done me a big favor.

**Comment by mrliptontea** [comment]
:ok_hand:
