### ISSUE TITLE
Problem with Adaptive theme

### ISSUE THREAD

**Issue by mPyth** [mrliptontea/sublime-text-sidebar-icons#2]
It is not clear how to rename the folder when [Adaptive Theme](https://www.sublimetext.com/blog/articles/the-adaptive-theme) is used. 
I've tried "Adaptive", "Adaptive - Theme", "Adaptive Theme", "Theme Adaptive" and "Theme - Adaptive" but neither of these combinations didn't work.
That information would be valuable.

**Comment by mrliptontea** [comment]
Hi,

That's a fair question, as I use a customized version of Adaptive Theme myself now, although it wasn't available when I last pushed anything to this repo.

The path should be `Theme - Default/adaptive`. But you may want/need to customize the theme as well to make icons looks pretty. To do that:

1. Copy `{Sublime Text}/Packages/Theme - Default.sublime-package/adaptive/Adaptive.sublime-theme` to `{Sublime Text}/Data/Packages/Theme - Default/adaptive/` (yes, this is where you will have your icons too).
2. Open `Adaptive.sublime-theme`. Find `icon_file_type` class.
3. Change it to something like
    ```json
    {
        "class": "icon_file_type",
        "layer0.opacity": 0.9,
        "content_margin": [8, 8]
    },
    ```

If there are still any issues, try changing the name of `Adaptive.sublime-theme` to name of your choice, move everything to a different folder and change theme to that newly created.

**Comment by mPyth** [comment]
Thanks for the prompt answer - I just found the name of the folder by using PackageResourceViewer (command "Extract") and also noticed that icons are rendered blurry.
I've just wanted to post my findings and encounter on your answer - seems that you have answers for questions which are not asked yet.
Hats off !

**Comment by mPyth** [comment]
@mrliptontea
I've just did all the steps from your last post and icons are not blurry as before. Perfect !
Only issue I have noticed is related to icons **file_type_css.png** and **file_type_image.png** - instead of the new ones, icons from folder `Packages/Theme - Default.sublime-package/adaptive/` are shown.

**Comment by mrliptontea** [comment]
@mPyth yup, try changing theme file name and moving it all some else, like `Data/Packages/My Theme/` - basically create you custom theme.

**Comment by mPyth** [comment]
Just described problem with 'wrong' icons could be easily solved by deleting those from folder `Packages/Theme - Default.sublime-package/adaptive/`.

**Comment by mPyth** [comment]
@mrliptontea 
I've just seen your last comment - I've tried to do it (its better approach) but that new theme does not appear on the list of themes (by clicking on menu `Preferences -> Theme...` ).

**Comment by mrliptontea** [comment]
There is no reason why it wouldn't be - any `.sublime-theme` file in `Packages` folder will be visible there.

But if that's still the case, try setting it manually in Preferences file `"theme": "my-theme.sublime-theme"`

**Comment by mPyth** [comment]
Here is alternative approach:
In order to create the modified Adaptive theme beside folder copy/rename (after it is extracted by using PackageResourceViewer) it is needed to rename file `Adaptive.sublime-theme` (to avoid case with two themes with the same name) for example into `AdaptiveMod.sublime-theme`. After this action new theme will be available in list of themes.
This is better way to go than to delete problematic icons form original theme.
@mrliptontea Thanks for the tips.

**Comment by mrliptontea** [comment]
I was saying it from the start see https://github.com/mrliptontea/sublime-text-sidebar-icons/issues/2#issuecomment-342822708

But glad you made it work eventually 👍
